# Generated by Django 6.0.6 on 2026-07-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
