# Generated by Django 6.0.6 on 2026-07-25 06:47

import uuid
from django.db import migrations, models


def give_existing_reservations_their_own_group(apps, schema_editor):
    """AddField evaluates the default once, so every existing row would share
    one group_id and look like a single huge booking. Each pre-existing
    reservation was made on its own, so give it its own group."""
    Reservation = apps.get_model("cinema", "Reservation")
    for reservation in Reservation.objects.all().iterator():
        reservation.group_id = uuid.uuid4()
        reservation.save(update_fields=["group_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_reservation_customer_email_reservation_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="group_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.RunPython(
            give_existing_reservations_their_own_group,
            migrations.RunPython.noop,
        ),
    ]
