# Generated by Django 6.0.6 on 2026-07-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_auditorium_formats_and_yen_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("popcorn", "Popcorn"),
                            ("snacks", "Snacks"),
                            ("drinks", "Drinks"),
                            ("desserts", "Desserts"),
                        ],
                        default="snacks",
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("image_url", models.URLField(blank=True)),
                ("image_credit", models.CharField(blank=True, max_length=255)),
                ("image_source", models.CharField(blank=True, max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("unit_price", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_items",
                        to="cinema.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item__category", "item__name"],
            },
        ),
    ]
